const services = require('./todos_los_servicios.json');

const chapters = [
  { slug: 'cosecha-forestal', title: 'Cosecha', line: 'El comienzo de\nla operación.', image: '/images/actualizadas/cosecha-forestal.png', alt: 'Procesadora forestal junto a madera cosechada', kind: 'harvest', copy: 'Corte, extracción y carga. Operación mecanizada adaptada a las necesidades de cada cliente.', caption: 'Corte · Extracción · Carga', motion: 'El marco se abre del 75% al 100% del ancho. Escala de 1 a 1.08; título y descripción permanecen legibles mientras cambia el encuadre.' },
  { slug: 'transporte-forestal', title: 'Transporte', line: 'Conectar bosque\ne industria.', image: '/images/actualizadas/transporte-forestal.png', alt: 'Camión forestal junto a madera y equipo de carga', kind: 'transport', copy: 'Transporte de troncos y chips, acompañado por la logística de los equipos.', caption: 'Troncos · Chips · Logística', motion: 'Imagen situada a la derecha y texto en el margen izquierdo. Entrada lateral de recorrido corto y disolución hacia el acopio.' },
  { slug: 'playas-de-acopio', title: 'Acopio', line: 'Orden para\nabastecer.', image: '/images/servicios/playa_acopio_1.jpeg', alt: 'Equipos movilizando madera en una playa de acopio', kind: 'stock', copy: 'Descarga, movimientos internos y acondicionamiento de madera para organizar el abastecimiento industrial.', caption: 'Descarga · Organización · Abastecimiento', motion: 'Fotografía horizontal a sangre, fondo oscuro y texto al mismo margen del relato. Disolución amplia para conservar la continuidad con Transporte y Caminos.' },
  { slug: 'caminos-forestales', title: 'Caminos', line: 'Abrir camino.\nDar continuidad.', image: '/images/actualizadas/caminos-forestales.png', alt: 'Motoniveladora trabajando en un camino forestal de tierra', kind: 'roads', copy: 'Apertura, mantenimiento y consolidación de caminos forestales para acompañar el movimiento en campo.', caption: 'Apertura · Mantenimiento · Consolidación', motion: 'Panorama abierto como transición de la operación. Parallax vertical limitado al 5%, sin desplazar el texto ni sus enlaces.' },
  { slug: 'aprovechamiento-biomasa-forestal', title: 'Biomasa', line: 'El recurso\ncontinúa.', image: '/images/actualizadas/biomasa-forestal.png', alt: 'Equipo procesando material forestal para su aprovechamiento como biomasa', kind: 'biomass', copy: 'Aprovechamiento de biomasa forestal y scrap forestoindustrial para su transformación en energía renovable.', caption: 'Biomasa forestal · Aprovechamiento', motion: 'Encuadre cercano sobre material y maquinaria. Escala progresiva hasta 1.08 y salida por disolución, sin una textura artificial añadida.' },
  { slug: 'consultoria-forestal', title: 'Consultoría', line: 'Mirar el conjunto.\nPlanificar.', image: '/images/actualizadas/consultoria-forestal.png', alt: 'Vista aérea de plantaciones y paisaje forestal', kind: 'consulting', copy: 'Planes de abastecimiento, análisis de supply chain y estudios de productividad para la cadena forestoindustrial.', caption: 'Planificación · Abastecimiento · Productividad', motion: 'Vista aérea al 75% del ancho y composición pausada. Cierre del relato operativo antes de la pausa institucional.' },
];

module.exports = chapters.map((chapter, index) => {
  const service = services.find((item) => item.slug === chapter.slug);
  if (!service) throw new Error(`Servicio desconocido en storyboard V2: ${chapter.slug}`);
  return { ...chapter, number: String(index + 1).padStart(2, '0'), detail: chapter.slug === 'consultoria-forestal' ? '/consultoria/' : `/servicios/${chapter.slug}/`, sourceDescription: service.descripcion };
});
